- id: google_drive
  name: Google Drive
  description: Configure your Google Drive account to accept file uploads. Only files uploaded by this Galaxy instance can be read.
  configuration:
    type: googledrive
    oauth2_client_id: "{{ environment.oauth2_client_id }}"
    oauth2_client_secret: "{{ environment.oauth2_client_secret }}"
    writable: true
  environment:
    oauth2_client_id:
      type: secret
      vault_key: "file_source_secrets/google_drive/app_client_id"
    oauth2_client_secret:
      type: secret
      vault_key: "file_source_secrets/google_drive/app_client_secret"
