---
# main tasks file for galaxyprojectdotorg.galaxy_toolshed

# Deploy a Galaxy Tool Shed server
#   https://galaxyproject.org/

- include: static_setup.yml
  when: galaxy_toolshed_manage_static_setup

- include: database.yml
  when: galaxy_toolshed_manage_database
