---

- name: Install EPEL nginx
  yum:
    pkg: nginx
  notify:
    - restart nginx
    - supervisorctl restart nginx
  when: nginx_flavor != "galaxy"

- name: Install Galaxy nginx
  yum:
    pkg: nginx-galaxy
  notify:
    - restart nginx
    - supervisorctl restart nginx
  when: nginx_flavor == "galaxy"

- name: Set permissions on temporary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_conf_user | default('nginx') }}"
    group: "{{ nginx_conf_group | default('nginx') }}"
    mode: 0700
  with_items:
    - /var/lib/nginx
    - /var/lib/nginx/tmp

- name: Template nginx config file
  template:
    src: epel-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
    backup: yes
  notify:
    - restart nginx
    - supervisorctl restart nginx

- name: Create virtual host directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ nginx_conf_dir }}/sites-available"
    - "{{ nginx_conf_dir }}/sites-enabled"
  notify:
    - reload nginx
    - supervisorctl reload nginx

- name: Create config including virtual hosts
  copy:
    dest: "{{ nginx_conf_dir }}/conf.d/sites-enabled.conf"
    content: |
      ## This file is maintained by Ansible - CHANGES WILL BE OVERWRITTEN
      include {{ nginx_conf_dir }}/sites-enabled/*;
  notify:
    - reload nginx
    - supervisorctl reload nginx

- name: Set default server redirection
  copy:
    dest: "{{ nginx_conf_dir }}/default.d/redirect.conf"
    content: |
      ## This file is maintained by Ansible - CHANGES WILL BE OVERWRITTEN
      return 302 {{ nginx_default_redirect_uri }};
  when: nginx_default_redirect_uri is defined
  notify:
    - reload nginx
    - supervisorctl reload nginx
