---
# defaults file for galaxyprojectdotorg.proftpd

proftpd_ssl_src_dir: files/ssl

proftpd_galaxy_modules:
  - mod_sql.c
  - mod_sql_passwd.c
  - mod_sql_postgres.c

proftpd_galaxy_default_options:
  - AuthOrder: mod_sql.c
  - AuthPAM: 'off'
  - Umask: '077'
  - DefaultRoot: '~'
  - CreateHome: on dirmode 700

proftpd_virtualhosts: []

proftpd_display_connect_context: 'server'
proftpd_tls_context: 'server'
proftpd_galaxy_auth_context: 'server'

proftpd_tls_sesscache_timeout: 300
proftpd_tls_renegotiate: null
