name: Imaging
type: generic
id: imaging
items:
- sections: 
  - get_data
  - send_data
  - collection_operations
  - expression_tools
- id: general_text_tools_label
  text: General Text Tools
  type: label
- sections:
  - text_manipulation
  - filter_and_sort
  - join__subtract_and_group
  - datamash
- id: statistics_and_visualization_label
  text: Statistics and Visualization
  type: label
- sections:
  - statistics
  - machine_learning
  - graph_display_data
  - interactive_tools
- id: imaging_label
  text: Imaging
  type: label
- sections:
  - imaging
