name: Microbiology
type: generic
id: microgalaxy
items:
- sections: [get_data, send_data, collection_operations, expression_tools]
- id: general_text_tools_label
  text: General Text Tools
  type: label
- sections: [text_manipulation, filter_and_sort, join__subtract_and_group]
- id: genomic_file_manipulation_label
  text: Genomic File Manipulation
  type: label
- sections: [convert_formats, fasta_fastq, fastq_quality_control, sam_bam, bed, nanopore]
- id: common_genomics_tools_label
  text: Common Genomics Tools
  type: label
- sections: [operate_on_genomic_intervals]
- id: genomics_analysis_label
  text: Genomics Analysis
  type: label
- sections: [annotation, multiple_alignments, assembly, mapping]
- id: genomics_toolkits_label
  text: Genomics Toolkits
  type: label
- sections: [picard, deeptools, ncbi_blast_]
- id: metagenomics_label
  text: Metagenomics
  type: label
- sections: [metagenomic_analysis, qiime2, mothur]
- id: metabolomics_label
  text: Metabolomics
  type: label
- sections: [metabolomics]
- id: statistics_and_visualization_label
  text: Statistics and Visualization
  type: label
- sections: [graph_display_data, interactive_tools]
