---

shared_root: /work/galaxy

pulsar_drmaa_library_path: "{{ instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_yaml_config:
  staging_directory: "/scratch/03166/xcgalaxy/test/staging"
  persistence_directory: "{{ pulsar_root }}/var/persisted_data"
  tool_dependency_dir: "{{ instance_root }}/deps"
  job_metrics_config_file: "{{ pulsar_config_dir }}/job_metrics_conf.xml"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  managers:
    stampede:
      type: queued_drmaa_xsede
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 20
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 4
      postprocess_action_interval_max: 120
      min_polling_interval: 15
    stampede_nagios:
      type: queued_python
      min_polling_interval: 5

pulsar_install_environments:
  pyOpenSSL:
    PKG_CONFIG_PATH: "{{ instance_root }}/libffi/lib64/pkgconfig"
    CFLAGS: "-I{{ instance_root }}/openssl/include"
    LDFLAGS: "-L{{ instance_root }}/openssl/lib"
  pycurl:
    PYCURL_SSL_LIBRARY: "nss"
