---

- name: Create swarm scale directory
  file:
    path: "{{ swarm_scale_root }}"
    state: directory
    owner: "{{ galaxy_user }}"

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - python-virtualenv
    - openssl-devel

- name: Create swarm scale virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ swarm_scale_root }}"
    state: latest
  with_items:
    - pip
    - setuptools
    - ansible
    - shade
    - python-openstackclient
  become: yes
  become_user: "{{ galaxy_user }}"

- name: Create swarm scale playbook directory
  file:
    path: "{{ swarm_scale_root }}/{{ item }}"
    state: directory
    owner: "{{ galaxy_user }}"
  with_items:
    - etc/playbook

- name: Copy playbook files
  copy:
    src: "{{ item }}"
    dest: "{{ swarm_scale_root }}/etc/playbook/{{ item }}"
    owner: "{{ galaxy_user }}"
  with_items:
    - delete.yml
    - inc_spawn.yml
    - instance
    - inventory.head
    - inventory.spawn
    - leave.yml
    - spawn.yml

- name: Create per-cloud ssh_config
  template:
    src: "ssh_config.jetstream.j2"
    dest: "{{ swarm_scale_root }}/etc/playbook/ssh_config.{{ item }}"
    owner: "{{ galaxy_user }}"
  with_items: "{{ clouds_yaml.clouds.keys() }}"

- name: Install private data
  copy:
    content: "{{ item.content }}"
    dest: "{{ swarm_scale_root }}/etc/playbook/{{ item.dest }}"
    owner: "{{ galaxy_user }}"
    mode: "0400"
  with_items:
    - content: "{{ swarm_ssh_key }}"
      dest: "swarm_kp.pem"
    - content: "{{ clouds_yaml | to_nice_yaml }}"
      dest: "clouds.yaml"
