---

instance_root: /srv/galaxy/main
galaxy_branch: release_17.09
galaxy_user: g2main
galaxy_privileged_user: gxsrc
galaxy_instance_hostname: usegalaxy.org
galaxy_instance_codename: main
galaxy_cvmfs_repo: main.galaxyproject.org
galaxy_version_file: "{{ inventory_dir }}/files/galaxy/galaxy_version.yml"

nginx_srv: /srv/nginx
