---

paths:
  - path: /cvmfs/data.galaxyproject.org/managed
    path_types: unstructured
    action: rewrite
    source_directory: /cvmfs/data.galaxyproject.org/managed
    destination_directory: /pylon5/mc48nsp/xcgalaxy/data
