---
# tasks file for galaxyprojectdotorg.proftpd

- name: Comment Galaxy proftpd.conf options
  lineinfile:
    name: "{{ proftpd_config_file }}"
    regexp: '^(\s*{{ item | first }}\s.*)'
    backrefs: yes
    line: '#\1 # commented by Ansible'
    backup: yes
  with_flattened: 
    - "{{ proftpd_galaxy_default_options }}"
    - "{{ proftpd_galaxy_options | default([]) }}"
  notify:
    - reload proftpd

- name: Uncomment LoadModule directives for Galaxy
  lineinfile:
    name: "{{ proftpd_modules_config_file }}"
    regexp: '^#\s*(LoadModule\s+{{ item }}.*)$'
    backrefs: yes
    line: '\1 # uncommented by Ansible'
    backup: yes
  with_items: "{{ proftpd_galaxy_modules }}"
  notify:
    - reload proftpd

- name: Lookup Galaxy user UID
  command: id -u {{ galaxy_user }}
  register: galaxy_user_uid_out
  changed_when: no
  when: galaxy_user_uid is undefined

- name: Set Galaxy user UID fact
  set_fact:
    galaxy_user_uid: "{{ galaxy_user_uid_out.stdout }}"
  when: galaxy_user_uid is undefined

- name: Lookup Galaxy user GID
  command: id -g {{ galaxy_user }}
  register: galaxy_user_gid_out
  changed_when: no
  when: galaxy_user_gid is undefined

- name: Set Galaxy user GID fact
  set_fact:
    galaxy_user_gid: "{{ galaxy_user_gid_out.stdout }}"
  when: galaxy_user_gid is undefined

- name: Configure Galaxy authentication options
  template:
    src: galaxy_auth.conf.j2
    dest: "{{ proftpd_config_include_dir }}/10_galaxy_auth.conf"
    backup: yes
  notify:
    - reload proftpd
