---

## these vars are defined in the vaulted (secret) vars file
#
# used by: galaxyprojectdotorg.galaxy (templating job_conf.xml)
#galaxy_job_conf_amqp_url
#
# used by: galaxy_config var
#galaxy_config_database_connection
#galaxy_config_install_database_connection
#galaxy_config_admin_users
#galaxy_config_id_secret
#galaxy_config_biostar_key
#galaxy_config_sentry_dsn
#galaxy_config_amqp_internal_connection


## used by: other vars in this vars file
galaxy_log_dir: "{{ galaxy_root }}/log"

# instance_root and galaxy_root are set in the play
# these are the same on galaxy servers
# on pulsar servers, galaxy_root is a subdirectory of instance_root
#instance_root:
#galaxy_root:


## used by: the play itself
galaxy_system_group: G-803372
# also by usegalaxy_admin
galaxy_privileged_user: gxsrc

galaxy_root: /srv/galaxy/{{ galaxy_instance_codename }}
galaxy_server_dir: "/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/galaxy"


## used by: usegalaxy, usegalaxy_static
galaxy_instance_hostname: usegalaxy.org

usegalaxy_nagios_tools:
  - echo_main_w1_handler0
  - echo_main_w1_handler1
  - echo_main_w1_handler2
  - echo_main_w2_handler0
  - echo_main_w2_handler1
  - echo_main_w2_handler2
  - echo_main_cluster
  - echo_main_jetstream_iu
  - echo_main_jetstream_tacc
  - echo_main_stampede
  - echo_main_bridges


## used by: usegalaxy_admin
galaxy_log_archive_dir: /galaxy-repl/{{ galaxy_instance_codename }}/backup/log


## used by: galaxyprojectdotorg.galaxy
pip_virtualenv_command: "{{ galaxy_root }}/python/bin/virtualenv"

# some things are always local
galaxy_venv_dir: "/cvmfs/{{ galaxy_instance_codename }}.galaxyproject.org/venv"
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.ini"
galaxy_mutable_data_dir: "{{ galaxy_root }}/var"
galaxy_mutable_config_dir: "/galaxy-repl/{{ galaxy_instance_codename }}/config"

galaxy_admin_email_to: galaxy-lab@bx.psu.edu

base_app_main: &BASE_APP_MAIN

  # message box
  #message_box_visible: "True"
  #message_box_content: 'Galaxy will be unavailable between 10:00 AM - 5:00 PM EST (UTC -0500) <strong>Monday, November 21st</strong> due to filesystem maintenance. Running jobs may be interrupted during this period.'
  #message_box_content: 'Galaxy will be unavailable between 12:00 PM - 6:00 PM EST (UTC -0500) <strong>today</strong>, Tuesday, November 10th due to <a target="_blank" href="https://portal.tacc.utexas.edu/user-news/-/news/101798">filesystem maintenance</a>. Running jobs may be interrupted during this period.'
  #message_box_content: 'Galaxy now runs some (larger, multicore) jobs on <a target="_blank" href="http://jetstream-cloud.org/">Jetstream</a>, you may encounter a few problems related to this. We are working on these, and please feel free to report any errors you encounter.'
  #message_box_class: warning

  # this can be removed after 9/22 and the datatypes_conf.xml update
  gbrowse_display_sites: wormbase,tair,modencode_worm,modencode_fly
  ucsc_display_sites: main,archaea,ucla

  # secrets

  database_connection: "{{ galaxy_config_database_connection }}"
  install_database_connection: "sqlite:////cvmfs/main.galaxyproject.org/var/galaxy_main_install.sqlite?isolation_level=IMMEDIATE"
  id_secret: "{{ galaxy_config_id_secret }}"
  admin_users: "{{ galaxy_config_admin_users }}"
  biostar_key: "{{ galaxy_config_biostar_key }}"
  #sentry_dsn: "{{ galaxy_config_sentry_dsn }}"
  amqp_internal_connection: "{{ galaxy_config_amqp_internal_connection }}"

  # paths

  tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,/cvmfs/main.galaxyproject.org/config/shed_tool_conf.xml,{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  tool_dependency_dir: /galaxy/main/deps
  job_working_directory: /galaxy/main/jobdir
  tool_data_path: /galaxy-repl/main/tool_data
  nginx_upload_store: /galaxy-repl/main/upload
  nginx_upload_job_files_store: /galaxy-repl/main/upload_job_files
  ftp_upload_dir: /galaxy/main/ftp
  user_library_import_dir: /galaxy/main/ftp
  library_import_dir: /galaxy-repl/main/import
  galaxy_data_manager_data_path: /galaxy-repl/manageddata/data

  tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
  tool_data_table_config_path: "{{ galaxy_config_dir }}/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml"
  build_sites_config_file: "{{ galaxy_config_dir }}/build_sites.yml"
  #datatypes_config_file: "{{ galaxy_config_dir }}/datatypes_conf.xml"
  object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
  job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
  job_resource_params_file: "{{ galaxy_config_dir }}/job_resource_params_conf.xml"
  data_manager_config_file: "{{ galaxy_config_dir }}/data_manager_conf.xml"
  job_metrics_config_file: "{{ galaxy_config_dir }}/job_metrics_conf.xml"

  migrated_tools_config: "/cvmfs/main.galaxyproject.org/config/migrated_tools_conf.xml"
  shed_tool_data_table_config: "/cvmfs/main.galaxyproject.org/config/shed_tool_data_table_conf.xml"
  shed_data_manager_config_file: "/cvmfs/main.galaxyproject.org/config/shed_data_manager_conf.xml"
  integrated_tool_panel_config: "{{ galaxy_mutable_config_dir }}/integrated_tool_panel.xml"
  sanitize_whitelist_file: /galaxy-repl/main/config/sanitize_whitelist.txt

  #environment_setup_file: /galaxy/main/job_env.bash

  builds_file_path: "{{ galaxy_config_dir }}/builds.txt"
  ucsc_build_sites: "{{ galaxy_config_dir }}/ucsc_build_sites.txt"

  # interactive environments
  interactive_environment_plugins_directory: "{{ galaxy_root }}/interactive_environments/plugins"
  dynamic_proxy_manage: "False"
  dynamic_proxy_session_map: /srv/galaxy/main/var/gie_proxy_session_map.sqlite
  dynamic_proxy_bind_port: 4280
  dynamic_proxy_bind_ip: 0.0.0.0
  dynamic_proxy_debug: "True"
  dynamic_proxy_external_proxy: "True"
  dynamic_proxy_prefix: gie_proxy
  galaxy_infrastructure_url: https://usegalaxy.org
  #trust_ipython_notebook_conversion: "True"


  # general stuff

  database_engine_option_pool_size: 10
  database_engine_option_max_overflow: 20
  database_engine_option_server_side_cursors: "True"
  manage_dependency_relationships: "False"
  len_file_path: /galaxy-repl/localdata/chrom
  collect_outputs_from: job_working_directory
  smtp_server: localhost
  error_email_to: galaxy-bugs@bx.psu.edu
  activation_email: "Galaxy Activation <activate@galaxyproject.org>"
  instance_resource_url: "http://wiki.galaxyproject.org/Support"
  screencasts_url: "https://vimeo.com/galaxyproject"
  search_url: "http://galaxyproject.org/search/usegalaxy/"
  blacklist_file: "{{ galaxy_config_dir }}/disposable_email_blacklist.conf"
  registration_warning_message: "Please register only one account. The {{ galaxy_instance_hostname }} service is provided free of charge and has limited computational and data storage resources. <strong>Registration and usage of multiple accounts is tracked and such accounts are subject to termination and data deletion.</strong>"
  user_activation_on: "True"
  activation_grace_period: 6
  inactivity_box_content: "Your account has not been activated yet.  Feel free to browse around and see what's available, but you won't be able to upload data or run jobs until you have verified your email address."
  wiki_url: "http://wiki.galaxyproject.org/"
  terms_url: "https://{{ galaxy_instance_hostname }}/static/terms.html"
  ga_code: "UA-45719423-10"
  static_enabled: "True"
  enable_cloud_launch: "True"
  cloudlaunch_default_ami: ami-a7dbf6ce
  nginx_x_accel_redirect_base: /_x_accel_redirect
  nginx_upload_path: /_upload
  nginx_upload_job_files_path: /_job_files
  log_events: "False"
  log_actions: "False"
  debug: "False"
  use_interactive: "False"
  use_pbkdf2: "False"
  allow_user_deletion: "True"
  allow_user_dataset_purge: "True"
  enable_openid: "True"
  ftp_upload_site: "{{ galaxy_instance_hostname }}"
  enable_quotas: "True"
  track_jobs_in_database: "True"
  retry_metadata_internally: "False"
  retry_job_output_collection: 5
  cleanup_job: onsuccess
  biostar_url: "https://biostar.usegalaxy.org"
  biostar_key_name: biostar-login
  biostar_enable_bug_reports: "False"
  max_metadata_value_size: 1000000
  use_heartbeat: "True"
  heartbeat_interval: -1
  heartbeat_log: "{{ galaxy_log_dir }}/heartbeat_{server_name}.log"
  tool_search_limit: 30
  tool_name_boost: 12
  tool_section_boost: 5

  conda_copy_dependencies: "True"

  # stats
  statsd_host: "galaxy06.tacc.utexas.edu"
  statsd_port: "8125"
  statsd_prefix: "main"

# galaxy.ini contents
galaxy_config_hash:
  "app:main":
    <<: *BASE_APP_MAIN
    allow_user_impersonation: "False"
    new_file_path: /galaxy-repl/main/scratch2

impersonate_config_hash:
  "server:main_w1_impersonate":
    threadpool_workers: 5
    host: 0.0.0.0
    port: 9480
  "server:main_w2_impersonate":
    threadpool_workers: 5
    host: 0.0.0.0
    port: 9480
  "filter:proxy-prefix":
    use: "egg:PasteDeploy#prefix"
    prefix: /main/impersonate
  "app:main":
    <<: *BASE_APP_MAIN
    allow_user_impersonation: "True"
    "filter-with": proxy-prefix
    new_file_path: /galaxy-repl/main/scratch2

installer_config_hash:
  "server:main_w1_installer":
    threadpool_workers: 5
    host: 0.0.0.0
    port: 9999
  "app:main":
    <<: *BASE_APP_MAIN
    allow_user_impersonation: "False"
    new_file_path: /srv/galaxy/main/var/installer_tmp

datamanager_config_hash:
  "app:main":
    <<: *BASE_APP_MAIN
    new_file_path: /galaxy-repl/main/scratch2

# specifies config files to copy from the playbook
galaxy_config_files:
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_data_table_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_data_table_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_conf.xml
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/nagios_tool_conf.xml
    dest: "{{ galaxy_config_dir }}/nagios_tool_conf.xml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/object_store_conf.xml
    dest: "{{ galaxy_config['app:main']['object_store_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/data_manager_conf.xml
    dest: "{{ galaxy_config['app:main']['data_manager_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/tool_sheds_conf.xml
    dest: "{{ galaxy_config['app:main']['tool_sheds_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/job_metrics_conf.xml
    dest: "{{ galaxy_config['app:main']['job_metrics_config_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/job_resource_params_conf.xml
    dest: "{{ galaxy_config['app:main']['job_resource_params_file'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_stampede_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_stampede_actions.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_jetstream.yml
    dest: "{{ galaxy_config_dir }}/pulsar_jetstream.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/pulsar_jetstream_actions.yml
    dest: "{{ galaxy_config_dir }}/pulsar_jetstream_actions.yml"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/builds.txt
    dest: "{{ galaxy_config['app:main']['builds_file_path'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/ucsc_build_sites.txt
    dest: "{{ galaxy_config['app:main']['ucsc_build_sites'] }}"
  - src: files/galaxy/{{ galaxy_instance_hostname }}/config/disposable_email_blacklist.conf
    dest: "{{ galaxy_config['app:main']['blacklist_file'] }}"

# specifies config files to template from the playbook
galaxy_config_templates:
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/build_sites.yml.j2
    dest: "{{ galaxy_config['app:main']['build_sites_config_file'] }}"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/reports.ini.j2
    dest: "{{ galaxy_config_dir }}/reports.ini"
  - src: templates/galaxy/{{ galaxy_instance_hostname }}/config/uwsgi.ini.j2
    dest: "{{ galaxy_config_dir }}/uwsgi.ini"
